import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

const font = Geist();

export const metadata: Metadata = {
  title: "Opnbin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${font.className} antialiased dark`}>{children}</body>
    </html>
  );
}
